#include <linux/module.h>
#define INCLUDE_VERMAGIC
#include <linux/build-salt.h>
#include <linux/elfnote-lto.h>
#include <linux/export-internal.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

BUILD_SALT;
BUILD_LTO_INFO;

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__section(".gnu.linkonce.this_module") = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef CONFIG_RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

MODULE_INFO(depends, "");

MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*PRIMEX470-PRO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*PRIMEX570-PRO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ProArtX570-CREATORWIFI*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ProWSX570-ACE*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIIDARKHERO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIIFORMULA*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIIHERO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIIHERO(WI-FI)*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGMAXIMUSXIHERO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGMAXIMUSXIHERO(WI-FI)*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIIIMPACT*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXB550-EGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXB550-IGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX570-EGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX570-EGAMINGWIFIII*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX570-FGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX570-IGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXZ690-AGAMINGWIFID4*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGZENITHIIEXTREME*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGZENITHIIEXTREMEALPHA*:");
