#include <linux/module.h>
#define INCLUDE_VERMAGIC
#include <linux/build-salt.h>
#include <linux/elfnote-lto.h>
#include <linux/export-internal.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

BUILD_SALT;
BUILD_LTO_INFO;

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__section(".gnu.linkonce.this_module") = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef CONFIG_RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

MODULE_INFO(depends, "wmi");

MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*PRIMEX399-A*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*PRIMEX470-PRO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIEXTREME*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*CROSSHAIRVIHERO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIHERO(WI-FIAC)*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIHERO*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGCROSSHAIRVIIHERO(WI-FI)*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXB450-EGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXB450-FGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXB450-FGAMINGII*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXB450-IGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX399-EGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX470-FGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGSTRIXX470-IGAMING*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGZENITHEXTREME*:");
MODULE_ALIAS("dmi*:rvn*ASUSTeKCOMPUTERINC.*:rn*ROGZENITHEXTREMEALPHA*:");
